import UserProvider from "@/contexts/UserContext";
import "./globals.css";
import VisibleProvider from "@/contexts/VisibleContext";
import PayloadProvider from "@/contexts/PayLoadContext";
import AuthProvider from "@/contexts/AuthContext";
import SpotifyProvider from "@/contexts/SpotifyContext";
import PlayingProvider from "@/contexts/PlayingContext";
import Playing from "@/components/playing/Playing";

export const metadata = {
  title: "QiMusic",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.png',
  },
};

export default function RootLayout({ children }) {

  // https://gist.github.com/vic4key/9144dfeee432504fa750558fafef7e18
  // http://api.mp3.zing.vn/api/streaming/audio/ZW7FDBA8/320

  // lấy src = https://photo-resize-zmp3.zmdcdn.me/w240_r1x1_jpeg + {thum}

  return (
    <html lang="en">
      <head>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          rel="stylesheet"
        />
        <meta name="google-site-verification" content="qPr_3m_jtgVoFmOL2IRmvbU2OdtNkvMzWNbAkpMcueU" />
      </head>
      <body>
        <PlayingProvider>
          <SpotifyProvider>
            <UserProvider>
              <VisibleProvider>
                <AuthProvider>
                  <PayloadProvider>
                    {children}
                  </PayloadProvider>
                </AuthProvider>
              </VisibleProvider>
            </UserProvider>
          </SpotifyProvider>
        </PlayingProvider>
      </body>
    </html>
  );
}
